# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/cam_to_mem_system_ila_2_1.xci
# IP: The module: 'cam_to_mem_system_ila_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/bd_1d83.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1d83 || ORIG_REF_NAME==bd_1d83} -quiet] -quiet

# IP: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/bd_1d83_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1d83_ila_lib_0 || ORIG_REF_NAME==bd_1d83_ila_lib_0} -quiet] -quiet

# IP: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_1/bd_1d83_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1d83_g_inst_0 || ORIG_REF_NAME==bd_1d83_g_inst_0} -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1d83_ila_lib_0 || ORIG_REF_NAME==bd_1d83_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1d83_ila_lib_0 || ORIG_REF_NAME==bd_1d83_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/bd_1d83_ila_lib_0_ooc.xdc

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/bd_1d83_ooc.xdc

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/cam_to_mem_system_ila_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_to_mem_system_ila_2_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/cam_to_mem_system_ila_2_1.xci
# IP: The module: 'cam_to_mem_system_ila_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/bd_1d83.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1d83 || ORIG_REF_NAME==bd_1d83} -quiet] -quiet

# IP: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/bd_1d83_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1d83_ila_lib_0 || ORIG_REF_NAME==bd_1d83_ila_lib_0} -quiet] -quiet

# IP: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_1/bd_1d83_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1d83_g_inst_0 || ORIG_REF_NAME==bd_1d83_g_inst_0} -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1d83_ila_lib_0 || ORIG_REF_NAME==bd_1d83_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1d83_ila_lib_0 || ORIG_REF_NAME==bd_1d83_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/bd_1d83_ila_lib_0_ooc.xdc

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/bd_1d83_ooc.xdc

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/cam_to_mem_system_ila_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_to_mem_system_ila_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
