# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/niumu/Refocusing/camera_screen/camera_screen.runs/synth_1/cam_to_mem_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 4
set_param bd.open.in_stealth_mode 2
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/niumu/Refocusing/camera_screen/camera_screen.cache/wt [current_project]
set_property parent.project_path C:/Users/niumu/Refocusing/camera_screen/camera_screen.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/niumu/Refocusing/camera_screen/camera_screen.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/hdl/cam_to_mem_wrapper.v
add_files C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/sources_1/bd/cam_to_mem/cam_to_mem.bd
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_processing_system7_0_0/cam_to_mem_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_v_vid_in_axi4s_0_0/cam_to_mem_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_v_vid_in_axi4s_0_0/cam_to_mem_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_vdma_0_0/cam_to_mem_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_vdma_0_0/cam_to_mem_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_vdma_0_0/cam_to_mem_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_1/bd_f1d2_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_2/bd_f1d2_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_3/bd_f1d2_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_4/bd_f1d2_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_5/bd_f1d2_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_6/bd_f1d2_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_7/bd_f1d2_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_8/bd_f1d2_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_9/bd_f1d2_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_10/bd_f1d2_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_11/bd_f1d2_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_12/bd_f1d2_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_13/bd_f1d2_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_14/bd_f1d2_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_15/bd_f1d2_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_16/bd_f1d2_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_20/bd_f1d2_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_21/bd_f1d2_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_22/bd_f1d2_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_23/bd_f1d2_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_24/bd_f1d2_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_25/bd_f1d2_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_26/bd_f1d2_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_27/bd_f1d2_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_28/bd_f1d2_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_29/bd_f1d2_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_30/bd_f1d2_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_31/bd_f1d2_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_33/bd_f1d2_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_34/bd_f1d2_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_35/bd_f1d2_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_36/bd_f1d2_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_37/bd_f1d2_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/bd_0/ip/ip_38/bd_f1d2_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_rst_ps7_0_50M_1/cam_to_mem_rst_ps7_0_50M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_rst_ps7_0_50M_1/cam_to_mem_rst_ps7_0_50M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_1_0/cam_to_mem_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_1_0/cam_to_mem_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_proc_sys_reset_0_0/cam_to_mem_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_proc_sys_reset_0_0/cam_to_mem_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_v_axi4s_vid_out_0_0/cam_to_mem_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_v_axi4s_vid_out_0_0/cam_to_mem_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axis_subset_converter_0_0/cam_to_mem_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_proc_sys_reset_1_0/cam_to_mem_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_proc_sys_reset_1_0/cam_to_mem_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axis_data_fifo_0_0/cam_to_mem_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_v_tc_0_0/cam_to_mem_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_v_tc_0_0/cam_to_mem_v_tc_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/ip/ip_0/bd_1d83_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/bd_0/bd_1d83_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/cam_to_mem_system_ila_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_mem_intercon_imp_auto_pc_0/cam_to_mem_axi_mem_intercon_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_axi_mem_intercon_1_imp_auto_pc_0/cam_to_mem_axi_mem_intercon_1_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/cam_to_mem_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/constrs_1/new/camera_pins.xdc
set_property used_in_implementation false [get_files C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/constrs_1/new/camera_pins.xdc]
set_property processing_order LATE [get_files C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/constrs_1/new/camera_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/utils_1/imports/synth_1/cam_to_mem_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top cam_to_mem_wrapper -part xc7z020clg400-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cam_to_mem_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file cam_to_mem_wrapper_utilization_synth.rpt -pb cam_to_mem_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
