# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/camera_pins.xdc

# Block Designs: bd/cam_to_mem/cam_to_mem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem || ORIG_REF_NAME==cam_to_mem} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_processing_system7_0_0/cam_to_mem_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_processing_system7_0_0 || ORIG_REF_NAME==cam_to_mem_processing_system7_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_v_vid_in_axi4s_0_0/cam_to_mem_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cam_to_mem_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axi_vdma_0_0/cam_to_mem_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axi_vdma_0_0 || ORIG_REF_NAME==cam_to_mem_axi_vdma_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axi_smc_0/cam_to_mem_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axi_smc_0 || ORIG_REF_NAME==cam_to_mem_axi_smc_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_rst_ps7_0_50M_1/cam_to_mem_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_rst_ps7_0_50M_1 || ORIG_REF_NAME==cam_to_mem_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axi_mem_intercon_1/cam_to_mem_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axi_mem_intercon_1 || ORIG_REF_NAME==cam_to_mem_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_util_ds_buf_0_0 || ORIG_REF_NAME==cam_to_mem_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_1_0/cam_to_mem_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_util_ds_buf_1_0 || ORIG_REF_NAME==cam_to_mem_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_proc_sys_reset_0_0/cam_to_mem_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_proc_sys_reset_0_0 || ORIG_REF_NAME==cam_to_mem_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_v_axi4s_vid_out_0_0/cam_to_mem_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==cam_to_mem_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axi_mem_intercon_1_1/cam_to_mem_axi_mem_intercon_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axi_mem_intercon_1_1 || ORIG_REF_NAME==cam_to_mem_axi_mem_intercon_1_1} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axis_subset_converter_0_0/cam_to_mem_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axis_subset_converter_0_0 || ORIG_REF_NAME==cam_to_mem_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_proc_sys_reset_1_0/cam_to_mem_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_proc_sys_reset_1_0 || ORIG_REF_NAME==cam_to_mem_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axis_data_fifo_0_0/cam_to_mem_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axis_data_fifo_0_0 || ORIG_REF_NAME==cam_to_mem_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_v_tc_0_0/cam_to_mem_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_v_tc_0_0 || ORIG_REF_NAME==cam_to_mem_v_tc_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_xlslice_0_0/cam_to_mem_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_xlslice_0_0 || ORIG_REF_NAME==cam_to_mem_xlslice_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_xlslice_1_0/cam_to_mem_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_xlslice_1_0 || ORIG_REF_NAME==cam_to_mem_xlslice_1_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_xlslice_2_0/cam_to_mem_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_xlslice_2_0 || ORIG_REF_NAME==cam_to_mem_xlslice_2_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axis_downsampler_0_0/cam_to_mem_axis_downsampler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axis_downsampler_0_0 || ORIG_REF_NAME==cam_to_mem_axis_downsampler_0_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_system_ila_2_1/cam_to_mem_system_ila_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_system_ila_2_1 || ORIG_REF_NAME==cam_to_mem_system_ila_2_1} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axi_mem_intercon_imp_auto_pc_0/cam_to_mem_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==cam_to_mem_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/cam_to_mem/ip/cam_to_mem_axi_mem_intercon_1_imp_auto_pc_0/cam_to_mem_axi_mem_intercon_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cam_to_mem_axi_mem_intercon_1_imp_auto_pc_0 || ORIG_REF_NAME==cam_to_mem_axi_mem_intercon_1_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/cam_to_mem_ooc.xdc
