-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Tue May  5 11:08:30 2026
-- Host        : DanielsLaptop running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_f78e_smartconnect_0_0_stub.vhdl
-- Design      : bd_f78e_smartconnect_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    aclk : in STD_LOGIC;
    aclk1 : in STD_LOGIC;
    aclk2 : in STD_LOGIC;
    aclk3 : in STD_LOGIC;
    aclk4 : in STD_LOGIC;
    aresetn : in STD_LOGIC;
    S00_AXI_awaddr : in STD_LOGIC_VECTOR ( 18 downto 0 );
    S00_AXI_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S00_AXI_awvalid : in STD_LOGIC;
    S00_AXI_awready : out STD_LOGIC;
    S00_AXI_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S00_AXI_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    S00_AXI_wvalid : in STD_LOGIC;
    S00_AXI_wready : out STD_LOGIC;
    S00_AXI_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S00_AXI_bvalid : out STD_LOGIC;
    S00_AXI_bready : in STD_LOGIC;
    S00_AXI_araddr : in STD_LOGIC_VECTOR ( 18 downto 0 );
    S00_AXI_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S00_AXI_arvalid : in STD_LOGIC;
    S00_AXI_arready : out STD_LOGIC;
    S00_AXI_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S00_AXI_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S00_AXI_rvalid : out STD_LOGIC;
    S00_AXI_rready : in STD_LOGIC;
    M00_AXI_awaddr : out STD_LOGIC_VECTOR ( 6 downto 0 );
    M00_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M00_AXI_awvalid : out STD_LOGIC;
    M00_AXI_awready : in STD_LOGIC;
    M00_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M00_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M00_AXI_wvalid : out STD_LOGIC;
    M00_AXI_wready : in STD_LOGIC;
    M00_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M00_AXI_bvalid : in STD_LOGIC;
    M00_AXI_bready : out STD_LOGIC;
    M00_AXI_araddr : out STD_LOGIC_VECTOR ( 6 downto 0 );
    M00_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M00_AXI_arvalid : out STD_LOGIC;
    M00_AXI_arready : in STD_LOGIC;
    M00_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M00_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M00_AXI_rvalid : in STD_LOGIC;
    M00_AXI_rready : out STD_LOGIC;
    M01_AXI_awaddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M01_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M01_AXI_awvalid : out STD_LOGIC;
    M01_AXI_awready : in STD_LOGIC;
    M01_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M01_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M01_AXI_wvalid : out STD_LOGIC;
    M01_AXI_wready : in STD_LOGIC;
    M01_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M01_AXI_bvalid : in STD_LOGIC;
    M01_AXI_bready : out STD_LOGIC;
    M01_AXI_araddr : out STD_LOGIC_VECTOR ( 8 downto 0 );
    M01_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M01_AXI_arvalid : out STD_LOGIC;
    M01_AXI_arready : in STD_LOGIC;
    M01_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M01_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M01_AXI_rvalid : in STD_LOGIC;
    M01_AXI_rready : out STD_LOGIC;
    M02_AXI_awaddr : out STD_LOGIC_VECTOR ( 11 downto 0 );
    M02_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M02_AXI_awvalid : out STD_LOGIC;
    M02_AXI_awready : in STD_LOGIC;
    M02_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M02_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M02_AXI_wvalid : out STD_LOGIC;
    M02_AXI_wready : in STD_LOGIC;
    M02_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M02_AXI_bvalid : in STD_LOGIC;
    M02_AXI_bready : out STD_LOGIC;
    M02_AXI_araddr : out STD_LOGIC_VECTOR ( 11 downto 0 );
    M02_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M02_AXI_arvalid : out STD_LOGIC;
    M02_AXI_arready : in STD_LOGIC;
    M02_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M02_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M02_AXI_rvalid : in STD_LOGIC;
    M02_AXI_rready : out STD_LOGIC;
    M03_AXI_awaddr : out STD_LOGIC_VECTOR ( 15 downto 0 );
    M03_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M03_AXI_awvalid : out STD_LOGIC;
    M03_AXI_awready : in STD_LOGIC;
    M03_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M03_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M03_AXI_wvalid : out STD_LOGIC;
    M03_AXI_wready : in STD_LOGIC;
    M03_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M03_AXI_bvalid : in STD_LOGIC;
    M03_AXI_bready : out STD_LOGIC;
    M03_AXI_araddr : out STD_LOGIC_VECTOR ( 15 downto 0 );
    M03_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M03_AXI_arvalid : out STD_LOGIC;
    M03_AXI_arready : in STD_LOGIC;
    M03_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M03_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M03_AXI_rvalid : in STD_LOGIC;
    M03_AXI_rready : out STD_LOGIC;
    M04_AXI_awaddr : out STD_LOGIC_VECTOR ( 6 downto 0 );
    M04_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M04_AXI_awvalid : out STD_LOGIC;
    M04_AXI_awready : in STD_LOGIC;
    M04_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M04_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M04_AXI_wvalid : out STD_LOGIC;
    M04_AXI_wready : in STD_LOGIC;
    M04_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M04_AXI_bvalid : in STD_LOGIC;
    M04_AXI_bready : out STD_LOGIC;
    M04_AXI_araddr : out STD_LOGIC_VECTOR ( 6 downto 0 );
    M04_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M04_AXI_arvalid : out STD_LOGIC;
    M04_AXI_arready : in STD_LOGIC;
    M04_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M04_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M04_AXI_rvalid : in STD_LOGIC;
    M04_AXI_rready : out STD_LOGIC;
    M05_AXI_awid : out STD_LOGIC;
    M05_AXI_awaddr : out STD_LOGIC;
    M05_AXI_awlen : out STD_LOGIC;
    M05_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M05_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M05_AXI_awlock : out STD_LOGIC;
    M05_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M05_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M05_AXI_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M05_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M05_AXI_awuser : out STD_LOGIC;
    M05_AXI_awvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_awready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_wid : out STD_LOGIC;
    M05_AXI_wdata : out STD_LOGIC;
    M05_AXI_wstrb : out STD_LOGIC;
    M05_AXI_wlast : out STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_wuser : out STD_LOGIC;
    M05_AXI_wvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_wready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_bid : in STD_LOGIC;
    M05_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M05_AXI_buser : in STD_LOGIC;
    M05_AXI_bvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_bready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_arid : out STD_LOGIC;
    M05_AXI_araddr : out STD_LOGIC;
    M05_AXI_arlen : out STD_LOGIC;
    M05_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M05_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M05_AXI_arlock : out STD_LOGIC;
    M05_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M05_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M05_AXI_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M05_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M05_AXI_aruser : out STD_LOGIC;
    M05_AXI_arvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_arready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_rid : in STD_LOGIC;
    M05_AXI_rdata : in STD_LOGIC;
    M05_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M05_AXI_rlast : in STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_ruser : in STD_LOGIC;
    M05_AXI_rvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M05_AXI_rready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_awid : out STD_LOGIC;
    M06_AXI_awaddr : out STD_LOGIC;
    M06_AXI_awlen : out STD_LOGIC;
    M06_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M06_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M06_AXI_awlock : out STD_LOGIC;
    M06_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M06_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M06_AXI_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M06_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M06_AXI_awuser : out STD_LOGIC;
    M06_AXI_awvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_awready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_wid : out STD_LOGIC;
    M06_AXI_wdata : out STD_LOGIC;
    M06_AXI_wstrb : out STD_LOGIC;
    M06_AXI_wlast : out STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_wuser : out STD_LOGIC;
    M06_AXI_wvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_wready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_bid : in STD_LOGIC;
    M06_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M06_AXI_buser : in STD_LOGIC;
    M06_AXI_bvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_bready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_arid : out STD_LOGIC;
    M06_AXI_araddr : out STD_LOGIC;
    M06_AXI_arlen : out STD_LOGIC;
    M06_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M06_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M06_AXI_arlock : out STD_LOGIC;
    M06_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M06_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M06_AXI_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M06_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M06_AXI_aruser : out STD_LOGIC;
    M06_AXI_arvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_arready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_rid : in STD_LOGIC;
    M06_AXI_rdata : in STD_LOGIC;
    M06_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M06_AXI_rlast : in STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_ruser : in STD_LOGIC;
    M06_AXI_rvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M06_AXI_rready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_awid : out STD_LOGIC;
    M07_AXI_awaddr : out STD_LOGIC;
    M07_AXI_awlen : out STD_LOGIC;
    M07_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M07_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M07_AXI_awlock : out STD_LOGIC;
    M07_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M07_AXI_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_awuser : out STD_LOGIC;
    M07_AXI_awvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_awready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_wid : out STD_LOGIC;
    M07_AXI_wdata : out STD_LOGIC;
    M07_AXI_wstrb : out STD_LOGIC;
    M07_AXI_wlast : out STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_wuser : out STD_LOGIC;
    M07_AXI_wvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_wready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_bid : in STD_LOGIC;
    M07_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M07_AXI_buser : in STD_LOGIC;
    M07_AXI_bvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_bready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_arid : out STD_LOGIC;
    M07_AXI_araddr : out STD_LOGIC;
    M07_AXI_arlen : out STD_LOGIC;
    M07_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M07_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M07_AXI_arlock : out STD_LOGIC;
    M07_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M07_AXI_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M07_AXI_aruser : out STD_LOGIC;
    M07_AXI_arvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_arready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_rid : in STD_LOGIC;
    M07_AXI_rdata : in STD_LOGIC;
    M07_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M07_AXI_rlast : in STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_ruser : in STD_LOGIC;
    M07_AXI_rvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M07_AXI_rready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M08_AXI_awaddr : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M08_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M08_AXI_awvalid : out STD_LOGIC;
    M08_AXI_awready : in STD_LOGIC;
    M08_AXI_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M08_AXI_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M08_AXI_wvalid : out STD_LOGIC;
    M08_AXI_wready : in STD_LOGIC;
    M08_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M08_AXI_bvalid : in STD_LOGIC;
    M08_AXI_bready : out STD_LOGIC;
    M08_AXI_araddr : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M08_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M08_AXI_arvalid : out STD_LOGIC;
    M08_AXI_arready : in STD_LOGIC;
    M08_AXI_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    M08_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M08_AXI_rvalid : in STD_LOGIC;
    M08_AXI_rready : out STD_LOGIC;
    M09_AXI_awid : out STD_LOGIC;
    M09_AXI_awaddr : out STD_LOGIC;
    M09_AXI_awlen : out STD_LOGIC;
    M09_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_awlock : out STD_LOGIC;
    M09_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_awuser : out STD_LOGIC;
    M09_AXI_awvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_awready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_wid : out STD_LOGIC;
    M09_AXI_wdata : out STD_LOGIC;
    M09_AXI_wstrb : out STD_LOGIC;
    M09_AXI_wlast : out STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_wuser : out STD_LOGIC;
    M09_AXI_wvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_wready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_bid : in STD_LOGIC;
    M09_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_buser : in STD_LOGIC;
    M09_AXI_bvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_bready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_arid : out STD_LOGIC;
    M09_AXI_araddr : out STD_LOGIC;
    M09_AXI_arlen : out STD_LOGIC;
    M09_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_arlock : out STD_LOGIC;
    M09_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M09_AXI_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M09_AXI_aruser : out STD_LOGIC;
    M09_AXI_arvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_arready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_rid : in STD_LOGIC;
    M09_AXI_rdata : in STD_LOGIC;
    M09_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M09_AXI_rlast : in STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_ruser : in STD_LOGIC;
    M09_AXI_rvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M09_AXI_rready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_awid : out STD_LOGIC;
    M10_AXI_awaddr : out STD_LOGIC;
    M10_AXI_awlen : out STD_LOGIC;
    M10_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M10_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M10_AXI_awlock : out STD_LOGIC;
    M10_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M10_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M10_AXI_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M10_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M10_AXI_awuser : out STD_LOGIC;
    M10_AXI_awvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_awready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_wid : out STD_LOGIC;
    M10_AXI_wdata : out STD_LOGIC;
    M10_AXI_wstrb : out STD_LOGIC;
    M10_AXI_wlast : out STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_wuser : out STD_LOGIC;
    M10_AXI_wvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_wready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_bid : in STD_LOGIC;
    M10_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M10_AXI_buser : in STD_LOGIC;
    M10_AXI_bvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_bready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_arid : out STD_LOGIC;
    M10_AXI_araddr : out STD_LOGIC;
    M10_AXI_arlen : out STD_LOGIC;
    M10_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M10_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M10_AXI_arlock : out STD_LOGIC;
    M10_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M10_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M10_AXI_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M10_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M10_AXI_aruser : out STD_LOGIC;
    M10_AXI_arvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_arready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_rid : in STD_LOGIC;
    M10_AXI_rdata : in STD_LOGIC;
    M10_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M10_AXI_rlast : in STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_ruser : in STD_LOGIC;
    M10_AXI_rvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M10_AXI_rready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_awid : out STD_LOGIC;
    M11_AXI_awaddr : out STD_LOGIC;
    M11_AXI_awlen : out STD_LOGIC;
    M11_AXI_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M11_AXI_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M11_AXI_awlock : out STD_LOGIC;
    M11_AXI_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M11_AXI_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M11_AXI_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M11_AXI_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M11_AXI_awuser : out STD_LOGIC;
    M11_AXI_awvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_awready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_wid : out STD_LOGIC;
    M11_AXI_wdata : out STD_LOGIC;
    M11_AXI_wstrb : out STD_LOGIC;
    M11_AXI_wlast : out STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_wuser : out STD_LOGIC;
    M11_AXI_wvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_wready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_bid : in STD_LOGIC;
    M11_AXI_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M11_AXI_buser : in STD_LOGIC;
    M11_AXI_bvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_bready : out STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_arid : out STD_LOGIC;
    M11_AXI_araddr : out STD_LOGIC;
    M11_AXI_arlen : out STD_LOGIC;
    M11_AXI_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M11_AXI_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M11_AXI_arlock : out STD_LOGIC;
    M11_AXI_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M11_AXI_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M11_AXI_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M11_AXI_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M11_AXI_aruser : out STD_LOGIC;
    M11_AXI_arvalid : out STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_arready : in STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_rid : in STD_LOGIC;
    M11_AXI_rdata : in STD_LOGIC;
    M11_AXI_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M11_AXI_rlast : in STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_ruser : in STD_LOGIC;
    M11_AXI_rvalid : in STD_LOGIC_VECTOR ( 0 to 0 );
    M11_AXI_rready : out STD_LOGIC_VECTOR ( 0 to 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_f78e_smartconnect_0_0,bd_d1d4,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_f78e_smartconnect_0_0,bd_d1d4,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=smartconnect,x_ipVersion=1.0,x_ipCoreRevision=28,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "aclk,aclk1,aclk2,aclk3,aclk4,aresetn,S00_AXI_awaddr[18:0],S00_AXI_awprot[2:0],S00_AXI_awvalid,S00_AXI_awready,S00_AXI_wdata[31:0],S00_AXI_wstrb[3:0],S00_AXI_wvalid,S00_AXI_wready,S00_AXI_bresp[1:0],S00_AXI_bvalid,S00_AXI_bready,S00_AXI_araddr[18:0],S00_AXI_arprot[2:0],S00_AXI_arvalid,S00_AXI_arready,S00_AXI_rdata[31:0],S00_AXI_rresp[1:0],S00_AXI_rvalid,S00_AXI_rready,M00_AXI_awaddr[6:0],M00_AXI_awprot[2:0],M00_AXI_awvalid,M00_AXI_awready,M00_AXI_wdata[31:0],M00_AXI_wstrb[3:0],M00_AXI_wvalid,M00_AXI_wready,M00_AXI_bresp[1:0],M00_AXI_bvalid,M00_AXI_bready,M00_AXI_araddr[6:0],M00_AXI_arprot[2:0],M00_AXI_arvalid,M00_AXI_arready,M00_AXI_rdata[31:0],M00_AXI_rresp[1:0],M00_AXI_rvalid,M00_AXI_rready,M01_AXI_awaddr[8:0],M01_AXI_awprot[2:0],M01_AXI_awvalid,M01_AXI_awready,M01_AXI_wdata[31:0],M01_AXI_wstrb[3:0],M01_AXI_wvalid,M01_AXI_wready,M01_AXI_bresp[1:0],M01_AXI_bvalid,M01_AXI_bready,M01_AXI_araddr[8:0],M01_AXI_arprot[2:0],M01_AXI_arvalid,M01_AXI_arready,M01_AXI_rdata[31:0],M01_AXI_rresp[1:0],M01_AXI_rvalid,M01_AXI_rready,M02_AXI_awaddr[11:0],M02_AXI_awprot[2:0],M02_AXI_awvalid,M02_AXI_awready,M02_AXI_wdata[31:0],M02_AXI_wstrb[3:0],M02_AXI_wvalid,M02_AXI_wready,M02_AXI_bresp[1:0],M02_AXI_bvalid,M02_AXI_bready,M02_AXI_araddr[11:0],M02_AXI_arprot[2:0],M02_AXI_arvalid,M02_AXI_arready,M02_AXI_rdata[31:0],M02_AXI_rresp[1:0],M02_AXI_rvalid,M02_AXI_rready,M03_AXI_awaddr[15:0],M03_AXI_awprot[2:0],M03_AXI_awvalid,M03_AXI_awready,M03_AXI_wdata[31:0],M03_AXI_wstrb[3:0],M03_AXI_wvalid,M03_AXI_wready,M03_AXI_bresp[1:0],M03_AXI_bvalid,M03_AXI_bready,M03_AXI_araddr[15:0],M03_AXI_arprot[2:0],M03_AXI_arvalid,M03_AXI_arready,M03_AXI_rdata[31:0],M03_AXI_rresp[1:0],M03_AXI_rvalid,M03_AXI_rready,M04_AXI_awaddr[6:0],M04_AXI_awprot[2:0],M04_AXI_awvalid,M04_AXI_awready,M04_AXI_wdata[31:0],M04_AXI_wstrb[3:0],M04_AXI_wvalid,M04_AXI_wready,M04_AXI_bresp[1:0],M04_AXI_bvalid,M04_AXI_bready,M04_AXI_araddr[6:0],M04_AXI_arprot[2:0],M04_AXI_arvalid,M04_AXI_arready,M04_AXI_rdata[31:0],M04_AXI_rresp[1:0],M04_AXI_rvalid,M04_AXI_rready,M05_AXI_awid,M05_AXI_awaddr,M05_AXI_awlen,M05_AXI_awsize[2:0],M05_AXI_awburst[1:0],M05_AXI_awlock,M05_AXI_awcache[3:0],M05_AXI_awprot[2:0],M05_AXI_awregion[3:0],M05_AXI_awqos[3:0],M05_AXI_awuser,M05_AXI_awvalid[0:0],M05_AXI_awready[0:0],M05_AXI_wid,M05_AXI_wdata,M05_AXI_wstrb,M05_AXI_wlast[0:0],M05_AXI_wuser,M05_AXI_wvalid[0:0],M05_AXI_wready[0:0],M05_AXI_bid,M05_AXI_bresp[1:0],M05_AXI_buser,M05_AXI_bvalid[0:0],M05_AXI_bready[0:0],M05_AXI_arid,M05_AXI_araddr,M05_AXI_arlen,M05_AXI_arsize[2:0],M05_AXI_arburst[1:0],M05_AXI_arlock,M05_AXI_arcache[3:0],M05_AXI_arprot[2:0],M05_AXI_arregion[3:0],M05_AXI_arqos[3:0],M05_AXI_aruser,M05_AXI_arvalid[0:0],M05_AXI_arready[0:0],M05_AXI_rid,M05_AXI_rdata,M05_AXI_rresp[1:0],M05_AXI_rlast[0:0],M05_AXI_ruser,M05_AXI_rvalid[0:0],M05_AXI_rready[0:0],M06_AXI_awid,M06_AXI_awaddr,M06_AXI_awlen,M06_AXI_awsize[2:0],M06_AXI_awburst[1:0],M06_AXI_awlock,M06_AXI_awcache[3:0],M06_AXI_awprot[2:0],M06_AXI_awregion[3:0],M06_AXI_awqos[3:0],M06_AXI_awuser,M06_AXI_awvalid[0:0],M06_AXI_awready[0:0],M06_AXI_wid,M06_AXI_wdata,M06_AXI_wstrb,M06_AXI_wlast[0:0],M06_AXI_wuser,M06_AXI_wvalid[0:0],M06_AXI_wready[0:0],M06_AXI_bid,M06_AXI_bresp[1:0],M06_AXI_buser,M06_AXI_bvalid[0:0],M06_AXI_bready[0:0],M06_AXI_arid,M06_AXI_araddr,M06_AXI_arlen,M06_AXI_arsize[2:0],M06_AXI_arburst[1:0],M06_AXI_arlock,M06_AXI_arcache[3:0],M06_AXI_arprot[2:0],M06_AXI_arregion[3:0],M06_AXI_arqos[3:0],M06_AXI_aruser,M06_AXI_arvalid[0:0],M06_AXI_arready[0:0],M06_AXI_rid,M06_AXI_rdata,M06_AXI_rresp[1:0],M06_AXI_rlast[0:0],M06_AXI_ruser,M06_AXI_rvalid[0:0],M06_AXI_rready[0:0],M07_AXI_awid,M07_AXI_awaddr,M07_AXI_awlen,M07_AXI_awsize[2:0],M07_AXI_awburst[1:0],M07_AXI_awlock,M07_AXI_awcache[3:0],M07_AXI_awprot[2:0],M07_AXI_awregion[3:0],M07_AXI_awqos[3:0],M07_AXI_awuser,M07_AXI_awvalid[0:0],M07_AXI_awready[0:0],M07_AXI_wid,M07_AXI_wdata,M07_AXI_wstrb,M07_AXI_wlast[0:0],M07_AXI_wuser,M07_AXI_wvalid[0:0],M07_AXI_wready[0:0],M07_AXI_bid,M07_AXI_bresp[1:0],M07_AXI_buser,M07_AXI_bvalid[0:0],M07_AXI_bready[0:0],M07_AXI_arid,M07_AXI_araddr,M07_AXI_arlen,M07_AXI_arsize[2:0],M07_AXI_arburst[1:0],M07_AXI_arlock,M07_AXI_arcache[3:0],M07_AXI_arprot[2:0],M07_AXI_arregion[3:0],M07_AXI_arqos[3:0],M07_AXI_aruser,M07_AXI_arvalid[0:0],M07_AXI_arready[0:0],M07_AXI_rid,M07_AXI_rdata,M07_AXI_rresp[1:0],M07_AXI_rlast[0:0],M07_AXI_ruser,M07_AXI_rvalid[0:0],M07_AXI_rready[0:0],M08_AXI_awaddr[7:0],M08_AXI_awprot[2:0],M08_AXI_awvalid,M08_AXI_awready,M08_AXI_wdata[31:0],M08_AXI_wstrb[3:0],M08_AXI_wvalid,M08_AXI_wready,M08_AXI_bresp[1:0],M08_AXI_bvalid,M08_AXI_bready,M08_AXI_araddr[7:0],M08_AXI_arprot[2:0],M08_AXI_arvalid,M08_AXI_arready,M08_AXI_rdata[31:0],M08_AXI_rresp[1:0],M08_AXI_rvalid,M08_AXI_rready,M09_AXI_awid,M09_AXI_awaddr,M09_AXI_awlen,M09_AXI_awsize[2:0],M09_AXI_awburst[1:0],M09_AXI_awlock,M09_AXI_awcache[3:0],M09_AXI_awprot[2:0],M09_AXI_awregion[3:0],M09_AXI_awqos[3:0],M09_AXI_awuser,M09_AXI_awvalid[0:0],M09_AXI_awready[0:0],M09_AXI_wid,M09_AXI_wdata,M09_AXI_wstrb,M09_AXI_wlast[0:0],M09_AXI_wuser,M09_AXI_wvalid[0:0],M09_AXI_wready[0:0],M09_AXI_bid,M09_AXI_bresp[1:0],M09_AXI_buser,M09_AXI_bvalid[0:0],M09_AXI_bready[0:0],M09_AXI_arid,M09_AXI_araddr,M09_AXI_arlen,M09_AXI_arsize[2:0],M09_AXI_arburst[1:0],M09_AXI_arlock,M09_AXI_arcache[3:0],M09_AXI_arprot[2:0],M09_AXI_arregion[3:0],M09_AXI_arqos[3:0],M09_AXI_aruser,M09_AXI_arvalid[0:0],M09_AXI_arready[0:0],M09_AXI_rid,M09_AXI_rdata,M09_AXI_rresp[1:0],M09_AXI_rlast[0:0],M09_AXI_ruser,M09_AXI_rvalid[0:0],M09_AXI_rready[0:0],M10_AXI_awid,M10_AXI_awaddr,M10_AXI_awlen,M10_AXI_awsize[2:0],M10_AXI_awburst[1:0],M10_AXI_awlock,M10_AXI_awcache[3:0],M10_AXI_awprot[2:0],M10_AXI_awregion[3:0],M10_AXI_awqos[3:0],M10_AXI_awuser,M10_AXI_awvalid[0:0],M10_AXI_awready[0:0],M10_AXI_wid,M10_AXI_wdata,M10_AXI_wstrb,M10_AXI_wlast[0:0],M10_AXI_wuser,M10_AXI_wvalid[0:0],M10_AXI_wready[0:0],M10_AXI_bid,M10_AXI_bresp[1:0],M10_AXI_buser,M10_AXI_bvalid[0:0],M10_AXI_bready[0:0],M10_AXI_arid,M10_AXI_araddr,M10_AXI_arlen,M10_AXI_arsize[2:0],M10_AXI_arburst[1:0],M10_AXI_arlock,M10_AXI_arcache[3:0],M10_AXI_arprot[2:0],M10_AXI_arregion[3:0],M10_AXI_arqos[3:0],M10_AXI_aruser,M10_AXI_arvalid[0:0],M10_AXI_arready[0:0],M10_AXI_rid,M10_AXI_rdata,M10_AXI_rresp[1:0],M10_AXI_rlast[0:0],M10_AXI_ruser,M10_AXI_rvalid[0:0],M10_AXI_rready[0:0],M11_AXI_awid,M11_AXI_awaddr,M11_AXI_awlen,M11_AXI_awsize[2:0],M11_AXI_awburst[1:0],M11_AXI_awlock,M11_AXI_awcache[3:0],M11_AXI_awprot[2:0],M11_AXI_awregion[3:0],M11_AXI_awqos[3:0],M11_AXI_awuser,M11_AXI_awvalid[0:0],M11_AXI_awready[0:0],M11_AXI_wid,M11_AXI_wdata,M11_AXI_wstrb,M11_AXI_wlast[0:0],M11_AXI_wuser,M11_AXI_wvalid[0:0],M11_AXI_wready[0:0],M11_AXI_bid,M11_AXI_bresp[1:0],M11_AXI_buser,M11_AXI_bvalid[0:0],M11_AXI_bready[0:0],M11_AXI_arid,M11_AXI_araddr,M11_AXI_arlen,M11_AXI_arsize[2:0],M11_AXI_arburst[1:0],M11_AXI_arlock,M11_AXI_arcache[3:0],M11_AXI_arprot[2:0],M11_AXI_arregion[3:0],M11_AXI_arqos[3:0],M11_AXI_aruser,M11_AXI_arvalid[0:0],M11_AXI_arready[0:0],M11_AXI_rid,M11_AXI_rdata,M11_AXI_rresp[1:0],M11_AXI_rlast[0:0],M11_AXI_ruser,M11_AXI_rvalid[0:0],M11_AXI_rready[0:0]";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of aclk : signal is "xilinx.com:signal:clock:1.0 CLK.aclk CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of aclk : signal is "XIL_INTERFACENAME CLK.aclk, FREQ_HZ 150000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, ASSOCIATED_BUSIF M00_AXI:M01_AXI:M02_AXI:M03_AXI:M04_AXI:M05_AXI:M06_AXI:M07_AXI:M08_AXI:M09_AXI:M10_AXI:M11_AXI:S00_AXI, INSERT_VIP 0, ASSOCIATED_CLKEN s_sc_aclken";
  attribute X_INTERFACE_INFO of aclk1 : signal is "xilinx.com:signal:clock:1.0 CLK.aclk1 CLK";
  attribute X_INTERFACE_MODE of aclk1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of aclk1 : signal is "XIL_INTERFACENAME CLK.aclk1, FREQ_HZ 150000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of aclk2 : signal is "xilinx.com:signal:clock:1.0 CLK.aclk2 CLK";
  attribute X_INTERFACE_MODE of aclk2 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of aclk2 : signal is "XIL_INTERFACENAME CLK.aclk2, FREQ_HZ 150000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of aclk3 : signal is "xilinx.com:signal:clock:1.0 CLK.aclk3 CLK";
  attribute X_INTERFACE_MODE of aclk3 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of aclk3 : signal is "XIL_INTERFACENAME CLK.aclk3, FREQ_HZ 150000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of aclk4 : signal is "xilinx.com:signal:clock:1.0 CLK.aclk4 CLK";
  attribute X_INTERFACE_MODE of aclk4 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of aclk4 : signal is "XIL_INTERFACENAME CLK.aclk4, FREQ_HZ 150000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of aresetn : signal is "xilinx.com:signal:reset:1.0 RST.aresetn RST";
  attribute X_INTERFACE_MODE of aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of aresetn : signal is "XIL_INTERFACENAME RST.aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S00_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWADDR";
  attribute X_INTERFACE_MODE of S00_AXI_awaddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of S00_AXI_awaddr : signal is "XIL_INTERFACENAME S00_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 19, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of S00_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWPROT";
  attribute X_INTERFACE_INFO of S00_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWVALID";
  attribute X_INTERFACE_INFO of S00_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI AWREADY";
  attribute X_INTERFACE_INFO of S00_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WDATA";
  attribute X_INTERFACE_INFO of S00_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WSTRB";
  attribute X_INTERFACE_INFO of S00_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WVALID";
  attribute X_INTERFACE_INFO of S00_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI WREADY";
  attribute X_INTERFACE_INFO of S00_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 S00_AXI BRESP";
  attribute X_INTERFACE_INFO of S00_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI BVALID";
  attribute X_INTERFACE_INFO of S00_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI BREADY";
  attribute X_INTERFACE_INFO of S00_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARADDR";
  attribute X_INTERFACE_INFO of S00_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARPROT";
  attribute X_INTERFACE_INFO of S00_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARVALID";
  attribute X_INTERFACE_INFO of S00_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI ARREADY";
  attribute X_INTERFACE_INFO of S00_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RDATA";
  attribute X_INTERFACE_INFO of S00_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RRESP";
  attribute X_INTERFACE_INFO of S00_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RVALID";
  attribute X_INTERFACE_INFO of S00_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 S00_AXI RREADY";
  attribute X_INTERFACE_INFO of M00_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWADDR";
  attribute X_INTERFACE_MODE of M00_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M00_AXI_awaddr : signal is "XIL_INTERFACENAME M00_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 7, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M00_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWPROT";
  attribute X_INTERFACE_INFO of M00_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWVALID";
  attribute X_INTERFACE_INFO of M00_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI AWREADY";
  attribute X_INTERFACE_INFO of M00_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WDATA";
  attribute X_INTERFACE_INFO of M00_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WSTRB";
  attribute X_INTERFACE_INFO of M00_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WVALID";
  attribute X_INTERFACE_INFO of M00_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI WREADY";
  attribute X_INTERFACE_INFO of M00_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BRESP";
  attribute X_INTERFACE_INFO of M00_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BVALID";
  attribute X_INTERFACE_INFO of M00_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI BREADY";
  attribute X_INTERFACE_INFO of M00_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARADDR";
  attribute X_INTERFACE_INFO of M00_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARPROT";
  attribute X_INTERFACE_INFO of M00_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARVALID";
  attribute X_INTERFACE_INFO of M00_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI ARREADY";
  attribute X_INTERFACE_INFO of M00_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RDATA";
  attribute X_INTERFACE_INFO of M00_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RRESP";
  attribute X_INTERFACE_INFO of M00_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RVALID";
  attribute X_INTERFACE_INFO of M00_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M00_AXI RREADY";
  attribute X_INTERFACE_INFO of M01_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWADDR";
  attribute X_INTERFACE_MODE of M01_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M01_AXI_awaddr : signal is "XIL_INTERFACENAME M01_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 9, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M01_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWPROT";
  attribute X_INTERFACE_INFO of M01_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWVALID";
  attribute X_INTERFACE_INFO of M01_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI AWREADY";
  attribute X_INTERFACE_INFO of M01_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WDATA";
  attribute X_INTERFACE_INFO of M01_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WSTRB";
  attribute X_INTERFACE_INFO of M01_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WVALID";
  attribute X_INTERFACE_INFO of M01_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI WREADY";
  attribute X_INTERFACE_INFO of M01_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M01_AXI BRESP";
  attribute X_INTERFACE_INFO of M01_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI BVALID";
  attribute X_INTERFACE_INFO of M01_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI BREADY";
  attribute X_INTERFACE_INFO of M01_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARADDR";
  attribute X_INTERFACE_INFO of M01_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARPROT";
  attribute X_INTERFACE_INFO of M01_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARVALID";
  attribute X_INTERFACE_INFO of M01_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI ARREADY";
  attribute X_INTERFACE_INFO of M01_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RDATA";
  attribute X_INTERFACE_INFO of M01_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RRESP";
  attribute X_INTERFACE_INFO of M01_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RVALID";
  attribute X_INTERFACE_INFO of M01_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M01_AXI RREADY";
  attribute X_INTERFACE_INFO of M02_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWADDR";
  attribute X_INTERFACE_MODE of M02_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M02_AXI_awaddr : signal is "XIL_INTERFACENAME M02_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 12, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M02_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWPROT";
  attribute X_INTERFACE_INFO of M02_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWVALID";
  attribute X_INTERFACE_INFO of M02_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI AWREADY";
  attribute X_INTERFACE_INFO of M02_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WDATA";
  attribute X_INTERFACE_INFO of M02_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WSTRB";
  attribute X_INTERFACE_INFO of M02_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WVALID";
  attribute X_INTERFACE_INFO of M02_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI WREADY";
  attribute X_INTERFACE_INFO of M02_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M02_AXI BRESP";
  attribute X_INTERFACE_INFO of M02_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI BVALID";
  attribute X_INTERFACE_INFO of M02_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI BREADY";
  attribute X_INTERFACE_INFO of M02_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARADDR";
  attribute X_INTERFACE_INFO of M02_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARPROT";
  attribute X_INTERFACE_INFO of M02_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARVALID";
  attribute X_INTERFACE_INFO of M02_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI ARREADY";
  attribute X_INTERFACE_INFO of M02_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RDATA";
  attribute X_INTERFACE_INFO of M02_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RRESP";
  attribute X_INTERFACE_INFO of M02_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RVALID";
  attribute X_INTERFACE_INFO of M02_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M02_AXI RREADY";
  attribute X_INTERFACE_INFO of M03_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWADDR";
  attribute X_INTERFACE_MODE of M03_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M03_AXI_awaddr : signal is "XIL_INTERFACENAME M03_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 16, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M03_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWPROT";
  attribute X_INTERFACE_INFO of M03_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWVALID";
  attribute X_INTERFACE_INFO of M03_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI AWREADY";
  attribute X_INTERFACE_INFO of M03_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WDATA";
  attribute X_INTERFACE_INFO of M03_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WSTRB";
  attribute X_INTERFACE_INFO of M03_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WVALID";
  attribute X_INTERFACE_INFO of M03_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI WREADY";
  attribute X_INTERFACE_INFO of M03_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BRESP";
  attribute X_INTERFACE_INFO of M03_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BVALID";
  attribute X_INTERFACE_INFO of M03_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI BREADY";
  attribute X_INTERFACE_INFO of M03_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARADDR";
  attribute X_INTERFACE_INFO of M03_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARPROT";
  attribute X_INTERFACE_INFO of M03_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARVALID";
  attribute X_INTERFACE_INFO of M03_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI ARREADY";
  attribute X_INTERFACE_INFO of M03_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RDATA";
  attribute X_INTERFACE_INFO of M03_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RRESP";
  attribute X_INTERFACE_INFO of M03_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RVALID";
  attribute X_INTERFACE_INFO of M03_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M03_AXI RREADY";
  attribute X_INTERFACE_INFO of M04_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWADDR";
  attribute X_INTERFACE_MODE of M04_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M04_AXI_awaddr : signal is "XIL_INTERFACENAME M04_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 7, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M04_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWPROT";
  attribute X_INTERFACE_INFO of M04_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWVALID";
  attribute X_INTERFACE_INFO of M04_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI AWREADY";
  attribute X_INTERFACE_INFO of M04_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WDATA";
  attribute X_INTERFACE_INFO of M04_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WSTRB";
  attribute X_INTERFACE_INFO of M04_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WVALID";
  attribute X_INTERFACE_INFO of M04_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI WREADY";
  attribute X_INTERFACE_INFO of M04_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M04_AXI BRESP";
  attribute X_INTERFACE_INFO of M04_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI BVALID";
  attribute X_INTERFACE_INFO of M04_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI BREADY";
  attribute X_INTERFACE_INFO of M04_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARADDR";
  attribute X_INTERFACE_INFO of M04_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARPROT";
  attribute X_INTERFACE_INFO of M04_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARVALID";
  attribute X_INTERFACE_INFO of M04_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI ARREADY";
  attribute X_INTERFACE_INFO of M04_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RDATA";
  attribute X_INTERFACE_INFO of M04_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RRESP";
  attribute X_INTERFACE_INFO of M04_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RVALID";
  attribute X_INTERFACE_INFO of M04_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M04_AXI RREADY";
  attribute X_INTERFACE_INFO of M05_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWID";
  attribute X_INTERFACE_MODE of M05_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M05_AXI_awid : signal is "XIL_INTERFACENAME M05_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M05_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWADDR";
  attribute X_INTERFACE_INFO of M05_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWLEN";
  attribute X_INTERFACE_INFO of M05_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M05_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWBURST";
  attribute X_INTERFACE_INFO of M05_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M05_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M05_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWPROT";
  attribute X_INTERFACE_INFO of M05_AXI_awregion : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWREGION";
  attribute X_INTERFACE_INFO of M05_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWQOS";
  attribute X_INTERFACE_INFO of M05_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWUSER";
  attribute X_INTERFACE_INFO of M05_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWVALID";
  attribute X_INTERFACE_INFO of M05_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI AWREADY";
  attribute X_INTERFACE_INFO of M05_AXI_wid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WID";
  attribute X_INTERFACE_INFO of M05_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WDATA";
  attribute X_INTERFACE_INFO of M05_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WSTRB";
  attribute X_INTERFACE_INFO of M05_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WLAST";
  attribute X_INTERFACE_INFO of M05_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WUSER";
  attribute X_INTERFACE_INFO of M05_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WVALID";
  attribute X_INTERFACE_INFO of M05_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI WREADY";
  attribute X_INTERFACE_INFO of M05_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BID";
  attribute X_INTERFACE_INFO of M05_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BRESP";
  attribute X_INTERFACE_INFO of M05_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BUSER";
  attribute X_INTERFACE_INFO of M05_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BVALID";
  attribute X_INTERFACE_INFO of M05_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI BREADY";
  attribute X_INTERFACE_INFO of M05_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARID";
  attribute X_INTERFACE_INFO of M05_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARADDR";
  attribute X_INTERFACE_INFO of M05_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARLEN";
  attribute X_INTERFACE_INFO of M05_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M05_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARBURST";
  attribute X_INTERFACE_INFO of M05_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M05_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M05_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARPROT";
  attribute X_INTERFACE_INFO of M05_AXI_arregion : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARREGION";
  attribute X_INTERFACE_INFO of M05_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARQOS";
  attribute X_INTERFACE_INFO of M05_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARUSER";
  attribute X_INTERFACE_INFO of M05_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARVALID";
  attribute X_INTERFACE_INFO of M05_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI ARREADY";
  attribute X_INTERFACE_INFO of M05_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RID";
  attribute X_INTERFACE_INFO of M05_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RDATA";
  attribute X_INTERFACE_INFO of M05_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RRESP";
  attribute X_INTERFACE_INFO of M05_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RLAST";
  attribute X_INTERFACE_INFO of M05_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RUSER";
  attribute X_INTERFACE_INFO of M05_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RVALID";
  attribute X_INTERFACE_INFO of M05_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M05_AXI RREADY";
  attribute X_INTERFACE_INFO of M06_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWID";
  attribute X_INTERFACE_MODE of M06_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M06_AXI_awid : signal is "XIL_INTERFACENAME M06_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M06_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWADDR";
  attribute X_INTERFACE_INFO of M06_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWLEN";
  attribute X_INTERFACE_INFO of M06_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M06_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWBURST";
  attribute X_INTERFACE_INFO of M06_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M06_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M06_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWPROT";
  attribute X_INTERFACE_INFO of M06_AXI_awregion : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWREGION";
  attribute X_INTERFACE_INFO of M06_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWQOS";
  attribute X_INTERFACE_INFO of M06_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWUSER";
  attribute X_INTERFACE_INFO of M06_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWVALID";
  attribute X_INTERFACE_INFO of M06_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI AWREADY";
  attribute X_INTERFACE_INFO of M06_AXI_wid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WID";
  attribute X_INTERFACE_INFO of M06_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WDATA";
  attribute X_INTERFACE_INFO of M06_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WSTRB";
  attribute X_INTERFACE_INFO of M06_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WLAST";
  attribute X_INTERFACE_INFO of M06_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WUSER";
  attribute X_INTERFACE_INFO of M06_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WVALID";
  attribute X_INTERFACE_INFO of M06_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI WREADY";
  attribute X_INTERFACE_INFO of M06_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BID";
  attribute X_INTERFACE_INFO of M06_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BRESP";
  attribute X_INTERFACE_INFO of M06_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BUSER";
  attribute X_INTERFACE_INFO of M06_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BVALID";
  attribute X_INTERFACE_INFO of M06_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI BREADY";
  attribute X_INTERFACE_INFO of M06_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARID";
  attribute X_INTERFACE_INFO of M06_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARADDR";
  attribute X_INTERFACE_INFO of M06_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARLEN";
  attribute X_INTERFACE_INFO of M06_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M06_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARBURST";
  attribute X_INTERFACE_INFO of M06_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M06_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M06_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARPROT";
  attribute X_INTERFACE_INFO of M06_AXI_arregion : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARREGION";
  attribute X_INTERFACE_INFO of M06_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARQOS";
  attribute X_INTERFACE_INFO of M06_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARUSER";
  attribute X_INTERFACE_INFO of M06_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARVALID";
  attribute X_INTERFACE_INFO of M06_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI ARREADY";
  attribute X_INTERFACE_INFO of M06_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RID";
  attribute X_INTERFACE_INFO of M06_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RDATA";
  attribute X_INTERFACE_INFO of M06_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RRESP";
  attribute X_INTERFACE_INFO of M06_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RLAST";
  attribute X_INTERFACE_INFO of M06_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RUSER";
  attribute X_INTERFACE_INFO of M06_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RVALID";
  attribute X_INTERFACE_INFO of M06_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M06_AXI RREADY";
  attribute X_INTERFACE_INFO of M07_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWID";
  attribute X_INTERFACE_MODE of M07_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M07_AXI_awid : signal is "XIL_INTERFACENAME M07_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M07_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWADDR";
  attribute X_INTERFACE_INFO of M07_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWLEN";
  attribute X_INTERFACE_INFO of M07_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M07_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWBURST";
  attribute X_INTERFACE_INFO of M07_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M07_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M07_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWPROT";
  attribute X_INTERFACE_INFO of M07_AXI_awregion : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWREGION";
  attribute X_INTERFACE_INFO of M07_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWQOS";
  attribute X_INTERFACE_INFO of M07_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWUSER";
  attribute X_INTERFACE_INFO of M07_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWVALID";
  attribute X_INTERFACE_INFO of M07_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI AWREADY";
  attribute X_INTERFACE_INFO of M07_AXI_wid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WID";
  attribute X_INTERFACE_INFO of M07_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WDATA";
  attribute X_INTERFACE_INFO of M07_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WSTRB";
  attribute X_INTERFACE_INFO of M07_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WLAST";
  attribute X_INTERFACE_INFO of M07_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WUSER";
  attribute X_INTERFACE_INFO of M07_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WVALID";
  attribute X_INTERFACE_INFO of M07_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI WREADY";
  attribute X_INTERFACE_INFO of M07_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BID";
  attribute X_INTERFACE_INFO of M07_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BRESP";
  attribute X_INTERFACE_INFO of M07_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BUSER";
  attribute X_INTERFACE_INFO of M07_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BVALID";
  attribute X_INTERFACE_INFO of M07_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI BREADY";
  attribute X_INTERFACE_INFO of M07_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARID";
  attribute X_INTERFACE_INFO of M07_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARADDR";
  attribute X_INTERFACE_INFO of M07_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARLEN";
  attribute X_INTERFACE_INFO of M07_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M07_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARBURST";
  attribute X_INTERFACE_INFO of M07_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M07_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M07_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARPROT";
  attribute X_INTERFACE_INFO of M07_AXI_arregion : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARREGION";
  attribute X_INTERFACE_INFO of M07_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARQOS";
  attribute X_INTERFACE_INFO of M07_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARUSER";
  attribute X_INTERFACE_INFO of M07_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARVALID";
  attribute X_INTERFACE_INFO of M07_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI ARREADY";
  attribute X_INTERFACE_INFO of M07_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RID";
  attribute X_INTERFACE_INFO of M07_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RDATA";
  attribute X_INTERFACE_INFO of M07_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RRESP";
  attribute X_INTERFACE_INFO of M07_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RLAST";
  attribute X_INTERFACE_INFO of M07_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RUSER";
  attribute X_INTERFACE_INFO of M07_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RVALID";
  attribute X_INTERFACE_INFO of M07_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M07_AXI RREADY";
  attribute X_INTERFACE_INFO of M08_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWADDR";
  attribute X_INTERFACE_MODE of M08_AXI_awaddr : signal is "master";
  attribute X_INTERFACE_PARAMETER of M08_AXI_awaddr : signal is "XIL_INTERFACENAME M08_AXI, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 8, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M08_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWPROT";
  attribute X_INTERFACE_INFO of M08_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWVALID";
  attribute X_INTERFACE_INFO of M08_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI AWREADY";
  attribute X_INTERFACE_INFO of M08_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WDATA";
  attribute X_INTERFACE_INFO of M08_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WSTRB";
  attribute X_INTERFACE_INFO of M08_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WVALID";
  attribute X_INTERFACE_INFO of M08_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI WREADY";
  attribute X_INTERFACE_INFO of M08_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M08_AXI BRESP";
  attribute X_INTERFACE_INFO of M08_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI BVALID";
  attribute X_INTERFACE_INFO of M08_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI BREADY";
  attribute X_INTERFACE_INFO of M08_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARADDR";
  attribute X_INTERFACE_INFO of M08_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARPROT";
  attribute X_INTERFACE_INFO of M08_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARVALID";
  attribute X_INTERFACE_INFO of M08_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI ARREADY";
  attribute X_INTERFACE_INFO of M08_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RDATA";
  attribute X_INTERFACE_INFO of M08_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RRESP";
  attribute X_INTERFACE_INFO of M08_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RVALID";
  attribute X_INTERFACE_INFO of M08_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M08_AXI RREADY";
  attribute X_INTERFACE_INFO of M09_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWID";
  attribute X_INTERFACE_MODE of M09_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M09_AXI_awid : signal is "XIL_INTERFACENAME M09_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M09_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWADDR";
  attribute X_INTERFACE_INFO of M09_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWLEN";
  attribute X_INTERFACE_INFO of M09_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M09_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWBURST";
  attribute X_INTERFACE_INFO of M09_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M09_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M09_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWPROT";
  attribute X_INTERFACE_INFO of M09_AXI_awregion : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWREGION";
  attribute X_INTERFACE_INFO of M09_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWQOS";
  attribute X_INTERFACE_INFO of M09_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWUSER";
  attribute X_INTERFACE_INFO of M09_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWVALID";
  attribute X_INTERFACE_INFO of M09_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI AWREADY";
  attribute X_INTERFACE_INFO of M09_AXI_wid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WID";
  attribute X_INTERFACE_INFO of M09_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WDATA";
  attribute X_INTERFACE_INFO of M09_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WSTRB";
  attribute X_INTERFACE_INFO of M09_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WLAST";
  attribute X_INTERFACE_INFO of M09_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WUSER";
  attribute X_INTERFACE_INFO of M09_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WVALID";
  attribute X_INTERFACE_INFO of M09_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI WREADY";
  attribute X_INTERFACE_INFO of M09_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BID";
  attribute X_INTERFACE_INFO of M09_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BRESP";
  attribute X_INTERFACE_INFO of M09_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BUSER";
  attribute X_INTERFACE_INFO of M09_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BVALID";
  attribute X_INTERFACE_INFO of M09_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI BREADY";
  attribute X_INTERFACE_INFO of M09_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARID";
  attribute X_INTERFACE_INFO of M09_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARADDR";
  attribute X_INTERFACE_INFO of M09_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARLEN";
  attribute X_INTERFACE_INFO of M09_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M09_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARBURST";
  attribute X_INTERFACE_INFO of M09_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M09_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M09_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARPROT";
  attribute X_INTERFACE_INFO of M09_AXI_arregion : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARREGION";
  attribute X_INTERFACE_INFO of M09_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARQOS";
  attribute X_INTERFACE_INFO of M09_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARUSER";
  attribute X_INTERFACE_INFO of M09_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARVALID";
  attribute X_INTERFACE_INFO of M09_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI ARREADY";
  attribute X_INTERFACE_INFO of M09_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RID";
  attribute X_INTERFACE_INFO of M09_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RDATA";
  attribute X_INTERFACE_INFO of M09_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RRESP";
  attribute X_INTERFACE_INFO of M09_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RLAST";
  attribute X_INTERFACE_INFO of M09_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RUSER";
  attribute X_INTERFACE_INFO of M09_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RVALID";
  attribute X_INTERFACE_INFO of M09_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M09_AXI RREADY";
  attribute X_INTERFACE_INFO of M10_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWID";
  attribute X_INTERFACE_MODE of M10_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M10_AXI_awid : signal is "XIL_INTERFACENAME M10_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M10_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWADDR";
  attribute X_INTERFACE_INFO of M10_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWLEN";
  attribute X_INTERFACE_INFO of M10_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M10_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWBURST";
  attribute X_INTERFACE_INFO of M10_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M10_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M10_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWPROT";
  attribute X_INTERFACE_INFO of M10_AXI_awregion : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWREGION";
  attribute X_INTERFACE_INFO of M10_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWQOS";
  attribute X_INTERFACE_INFO of M10_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWUSER";
  attribute X_INTERFACE_INFO of M10_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWVALID";
  attribute X_INTERFACE_INFO of M10_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI AWREADY";
  attribute X_INTERFACE_INFO of M10_AXI_wid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WID";
  attribute X_INTERFACE_INFO of M10_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WDATA";
  attribute X_INTERFACE_INFO of M10_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WSTRB";
  attribute X_INTERFACE_INFO of M10_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WLAST";
  attribute X_INTERFACE_INFO of M10_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WUSER";
  attribute X_INTERFACE_INFO of M10_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WVALID";
  attribute X_INTERFACE_INFO of M10_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI WREADY";
  attribute X_INTERFACE_INFO of M10_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BID";
  attribute X_INTERFACE_INFO of M10_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BRESP";
  attribute X_INTERFACE_INFO of M10_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BUSER";
  attribute X_INTERFACE_INFO of M10_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BVALID";
  attribute X_INTERFACE_INFO of M10_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI BREADY";
  attribute X_INTERFACE_INFO of M10_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARID";
  attribute X_INTERFACE_INFO of M10_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARADDR";
  attribute X_INTERFACE_INFO of M10_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARLEN";
  attribute X_INTERFACE_INFO of M10_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M10_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARBURST";
  attribute X_INTERFACE_INFO of M10_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M10_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M10_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARPROT";
  attribute X_INTERFACE_INFO of M10_AXI_arregion : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARREGION";
  attribute X_INTERFACE_INFO of M10_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARQOS";
  attribute X_INTERFACE_INFO of M10_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARUSER";
  attribute X_INTERFACE_INFO of M10_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARVALID";
  attribute X_INTERFACE_INFO of M10_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI ARREADY";
  attribute X_INTERFACE_INFO of M10_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RID";
  attribute X_INTERFACE_INFO of M10_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RDATA";
  attribute X_INTERFACE_INFO of M10_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RRESP";
  attribute X_INTERFACE_INFO of M10_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RLAST";
  attribute X_INTERFACE_INFO of M10_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RUSER";
  attribute X_INTERFACE_INFO of M10_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RVALID";
  attribute X_INTERFACE_INFO of M10_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M10_AXI RREADY";
  attribute X_INTERFACE_INFO of M11_AXI_awid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWID";
  attribute X_INTERFACE_MODE of M11_AXI_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of M11_AXI_awid : signal is "XIL_INTERFACENAME M11_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 150000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN cam_to_mem_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M11_AXI_awaddr : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWADDR";
  attribute X_INTERFACE_INFO of M11_AXI_awlen : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWLEN";
  attribute X_INTERFACE_INFO of M11_AXI_awsize : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWSIZE";
  attribute X_INTERFACE_INFO of M11_AXI_awburst : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWBURST";
  attribute X_INTERFACE_INFO of M11_AXI_awlock : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWLOCK";
  attribute X_INTERFACE_INFO of M11_AXI_awcache : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWCACHE";
  attribute X_INTERFACE_INFO of M11_AXI_awprot : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWPROT";
  attribute X_INTERFACE_INFO of M11_AXI_awregion : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWREGION";
  attribute X_INTERFACE_INFO of M11_AXI_awqos : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWQOS";
  attribute X_INTERFACE_INFO of M11_AXI_awuser : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWUSER";
  attribute X_INTERFACE_INFO of M11_AXI_awvalid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWVALID";
  attribute X_INTERFACE_INFO of M11_AXI_awready : signal is "xilinx.com:interface:aximm:1.0 M11_AXI AWREADY";
  attribute X_INTERFACE_INFO of M11_AXI_wid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI WID";
  attribute X_INTERFACE_INFO of M11_AXI_wdata : signal is "xilinx.com:interface:aximm:1.0 M11_AXI WDATA";
  attribute X_INTERFACE_INFO of M11_AXI_wstrb : signal is "xilinx.com:interface:aximm:1.0 M11_AXI WSTRB";
  attribute X_INTERFACE_INFO of M11_AXI_wlast : signal is "xilinx.com:interface:aximm:1.0 M11_AXI WLAST";
  attribute X_INTERFACE_INFO of M11_AXI_wuser : signal is "xilinx.com:interface:aximm:1.0 M11_AXI WUSER";
  attribute X_INTERFACE_INFO of M11_AXI_wvalid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI WVALID";
  attribute X_INTERFACE_INFO of M11_AXI_wready : signal is "xilinx.com:interface:aximm:1.0 M11_AXI WREADY";
  attribute X_INTERFACE_INFO of M11_AXI_bid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI BID";
  attribute X_INTERFACE_INFO of M11_AXI_bresp : signal is "xilinx.com:interface:aximm:1.0 M11_AXI BRESP";
  attribute X_INTERFACE_INFO of M11_AXI_buser : signal is "xilinx.com:interface:aximm:1.0 M11_AXI BUSER";
  attribute X_INTERFACE_INFO of M11_AXI_bvalid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI BVALID";
  attribute X_INTERFACE_INFO of M11_AXI_bready : signal is "xilinx.com:interface:aximm:1.0 M11_AXI BREADY";
  attribute X_INTERFACE_INFO of M11_AXI_arid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARID";
  attribute X_INTERFACE_INFO of M11_AXI_araddr : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARADDR";
  attribute X_INTERFACE_INFO of M11_AXI_arlen : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARLEN";
  attribute X_INTERFACE_INFO of M11_AXI_arsize : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARSIZE";
  attribute X_INTERFACE_INFO of M11_AXI_arburst : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARBURST";
  attribute X_INTERFACE_INFO of M11_AXI_arlock : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARLOCK";
  attribute X_INTERFACE_INFO of M11_AXI_arcache : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARCACHE";
  attribute X_INTERFACE_INFO of M11_AXI_arprot : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARPROT";
  attribute X_INTERFACE_INFO of M11_AXI_arregion : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARREGION";
  attribute X_INTERFACE_INFO of M11_AXI_arqos : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARQOS";
  attribute X_INTERFACE_INFO of M11_AXI_aruser : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARUSER";
  attribute X_INTERFACE_INFO of M11_AXI_arvalid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARVALID";
  attribute X_INTERFACE_INFO of M11_AXI_arready : signal is "xilinx.com:interface:aximm:1.0 M11_AXI ARREADY";
  attribute X_INTERFACE_INFO of M11_AXI_rid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI RID";
  attribute X_INTERFACE_INFO of M11_AXI_rdata : signal is "xilinx.com:interface:aximm:1.0 M11_AXI RDATA";
  attribute X_INTERFACE_INFO of M11_AXI_rresp : signal is "xilinx.com:interface:aximm:1.0 M11_AXI RRESP";
  attribute X_INTERFACE_INFO of M11_AXI_rlast : signal is "xilinx.com:interface:aximm:1.0 M11_AXI RLAST";
  attribute X_INTERFACE_INFO of M11_AXI_ruser : signal is "xilinx.com:interface:aximm:1.0 M11_AXI RUSER";
  attribute X_INTERFACE_INFO of M11_AXI_rvalid : signal is "xilinx.com:interface:aximm:1.0 M11_AXI RVALID";
  attribute X_INTERFACE_INFO of M11_AXI_rready : signal is "xilinx.com:interface:aximm:1.0 M11_AXI RREADY";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "bd_d1d4,Vivado 2025.2";
begin
end;
