# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0.xci
# IP: The module: 'cam_to_mem_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_to_mem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_to_mem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/niumu/Refocusing/camera_screen/camera_screen.srcs/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0.xci
# IP: The module: 'cam_to_mem_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_to_mem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/niumu/Refocusing/camera_screen/camera_screen.gen/sources_1/bd/cam_to_mem/ip/cam_to_mem_util_ds_buf_0_0/cam_to_mem_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_to_mem_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
